baseURL = "https://k-db.sysnetadm.ru/"

locale = "ru"
defaultContentLanguage = "ru"

title = "K-DB"

author = "SilNuxx"
copyright = "K-DB"

theme = "tailwind"

[markup]
    _merge = 'deep'

[params]
    subtitle = "Tested on myself"
    contentTypeName = "posts"

    showAuthor = true

    [params.header]
        logo = "logo.svg"
        title = ""

    [params.footer]
        since = 2026
        poweredby = false